<?php
namespace Admin\Controller;

use Admin\Controller\AppController;

/**
 * Categories Controller
 *
 * @property \Admin\Model\Table\CategoriesTable $Categories
 *
 * @method \Admin\Model\Entity\Category[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AdminController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('title', 'Admin  ');

    }
    public function index(){

    }
}
