<?php

namespace Admin\Controller;

use App\Controller\AppController as BaseController;
use Cake\Event\Event;

class AppController extends BaseController
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('admin');

        $this->loadComponent('Auth', [
            'authorize' => 'Controller',
            'authenticate' => [
                'Form'=>[
                    'fields'=>['username'=>'email', 'password'=>'password'],
                    'scope'=>['verified'=>'1'],
                    'userModel'=> 'Users'
                ]
            ],
            'loginRedirect' => [
                'controller' => 'Home',
                'action' => 'index'
            ],
            'logoutRedirect' => [
                'controller' => 'Users',
                'action' => 'login',
            ],
            'storage'=>'Session',
        ]);
    }
    public function isAuthorized($user)
    {
        if ($this->request->getParam('plugin') == 'Admin' && $this->Auth->user('role') == 'owner')  {
            return true;
        }
        else{
            return false;
        }
    }

}
