<?php

namespace Admin\Controller;

use App\Controller\AppController as BaseController;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class AppController extends BaseController
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->viewBuilder()->setLayout('admin');

        $this->loadComponent('Auth', [
            'authorize' => 'Controller',
            'authenticate' => [
                'Form'=>[
                    'fields'=>['username'=>'email', 'password'=>'password'],
                    'scope'=>['verified'=>'1'],
                    'userModel'=> 'Users'
                ]
            ],
            'loginRedirect' => [
                'controller' => 'Home',
                'action' => 'index'
            ],
            'logoutRedirect' => [
                'controller' => 'Users',
                'action' => 'login',
            ],
            'storage'=>'Session',
        ]);

        $user_role = $this->Auth->user('role');
        $user_id = $this->Auth->user('id');
        $this->set(compact('user_role','user_id'));

//        $this->loadModel('Shifts');
//        $statuses = $this->Shifts->find('all')->where(['user_id'=> $this->Auth->user('id')])->last();
//        if (isset($statuses)){
//            $status = $statuses->status;
//            $this->set('status',$status);
//        }
    }
    public function isAuthorized($user)
    {
//        if ($this->request->getParam('plugin') == 'Admin' && $this->Auth->user('role') == 'owner')  {
//            return true;
//        }
        if ($this->request->getParam('plugin') == 'Admin'){
            return true;
        }
        else{
            return false;
        }
    }
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

//        $this->request->allowMethod('ajax');
    }

}
