<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Admin\Model\Entity\Product;
use Cake\Utility\Security;

/**
 * Products Controller
 *
 * @property \Admin\Model\Table\ProductsTable $Products
 *
 * @method \Admin\Model\Entity\Product[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ProductsController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('title' ,'Products');
        $this->loadComponent('RequestHandler');



    }
    /**
     * View method
     *
     * @param string|null $id Product id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $product = $this->Products->get($id, [
            'contain' => ['Categories'],
        ]);

        $this->set('product', $product);

//        if($this->request->is('Ajax')) //Ajax Detection
//        {
//            $this->autoRender = false; // Set Render False
//            $this->response->body('Success');
//            return $this->response;
//        }
    }


    public function index()
    {
        $this->paginate = [
            'contain' => ['Categories','Typecategories']
        ];

//        $products = $this->Products->find()->where(['user_id' => $this->Auth->user()['id']]);

        $products = $this->paginate($this->Products->find('all')->where(['Products.user_id'=> $this->Auth->user('id')]));
        //        $products = $this->paginate($this->Products);
        $this->set(compact('products'));

    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */

    public function add()
    {
//        $this->autoRender = $this->layout = false;




        $product = $this->Products->newEntity();

        if ($this->request->is('post')) {
            $product = $this->Products->patchEntity($product, $this->request->getData());
            $product->user_id = $this->Auth->user('id');

            $imgname = $this->request->getData()['img']['name'];
            $imgtmp = $this->request->getData()['img']['tmp_name'];
            $imgext = substr(strrchr($imgname, "."), 1);
            $imgpath = "upload/" . Security::hash($imgname) . date('Y-m-d-H-i-s') . "." . $imgext;

            $product->img_name = $imgname;
            $product->img_path = $imgpath;
            $product->isset = '1';

            if ($this->Products->save($product) and move_uploaded_file($imgtmp, WWW_ROOT . $imgpath)) {

                $this->Flash->success(__('The product has been saved.'));

                return $this->redirect(['action' => 'index']);


            }
            $this->Flash->error(__('The product could not be saved. Please, try again.'));
        }
        $categories = $this->Products->Categories->find('list')->where(['user_id'=>$this->Auth->user('id')]);

//        $typecategories = $this->Categories->Typecategories->find('list')->where(['category_id'=> '']);

        $this->set(compact('product', 'categories'));



    }



    /**
     * Edit method
     *
     * @param string|null $id Product id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $product = $this->Products->get($id, [
            'contain' => ['Categories'],
        ]);
        if ($this->request->is(['post', 'put'])) {

            $imgname = $this->request->getData()['img']['name'];
            $imgtmp = $this->request->getData()['img']['tmp_name'];
            $imgext = substr(strrchr($imgname, "."), 1);
            $imgpath = "upload/" . Security::hash($imgname) . date('Y-m-d-H-i-s') . "." . $imgext;

            $this->Products->patchEntity($product, $this->request->getData());


            if ($imgname != '') {
                $product->img_name = $imgname;
                $product->img_path = $imgpath;
                move_uploaded_file($imgtmp, WWW_ROOT . $imgpath);
            }

            if ($this->Products->save($product)) {
                return $this->redirect(['action' => 'index']);
                $product->modified = date('Y-m-d H:i:s');
            }
            $this->Flash->error(__('Ошибка обновления вашей статьи.'));
        }
        $categories = $this->Products->Categories->find('list', ['limit' => 200])->where(['user_id'=>$this->Auth->user('id')]);
        $this->set(compact('product', 'categories'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Product id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $product = $this->Products->get($id);
        if ($this->Products->delete($product)) {
            $this->Flash->success(__('The product has been deleted.'));
        } else {
            $this->Flash->error(__('The product could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function search(){
//        $this->request->allowMethod('ajax');
        $this->loadModel("Typecategories");
        $keyword = $this->request->getQuery('keyword');

        $query = $this->Typecategories->find('all',[
            'conditions' => ['category_id'=>$keyword]
        ])->where(['user_id'=>$this->Auth->user('id')]);
        $this->set('keyword',$keyword);
        $this->set('typecategories',$query);

        $this->viewBuilder()->setLayout('');



//        $this->set('products', $query);
    }

}
