<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\Utility\Security;


class UsersController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('title','Users');

    }

    public function index(){
        $users = $this->paginate($this->Users);
        $this->set(compact('users'));
    }
}
