<?php
namespace App\Controller;

use App\Controller\AppController;


class HomeController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Admin.Categories');
        $this->loadModel('Admin.Products');

    }

    public function index()
    {
    }

    public function categories($id = null){

        $products = $this->Products->find('all')->where(['category_id'=>$id, 'isset'=>'1']);
        $this->set('products', $products);

        if ($this->request->is('ajax')){
            $a = 'asdasddsadsa';
            debug($a);
        }
    }
    public function view($id = null){
        $product = $this->Products->get($id, [
            'contain' => ['Categories'],
        ]);
        $this->set('product', $product);

    }

}
